[workspace]
resolver = "2"
members = [
    "cubegame", "cubegame-server",
]
default-members = ["cubegame"]

[workspace.package]
version = "0.1.0"
authors = ["Jaxson Pahukula <jaxpahu@gmail.com>"]
repository = "https://github.com/jaxsonp/cubegame"