[workspace]
resolver = "2"
members = [
    "cubegame_lib", "cubegame_client", "cubegame_server",
]
default-members = ["cubegame_client"]

[workspace.package]
version = "0.1.0"
authors = ["Jaxson Pahukula <jaxpahu@gmail.com>"]
repository = "https://github.com/jaxsonp/cubegame"

